version: "3.8"

services:
  api:
    build: .
    container_name: fastapi_notification_service
    restart: always
    ports:
      - "8100:8000"
    environment:
      MONGO_URI: "mongodb://mongo:27017"
